plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag
  - key: instance_type
    prefix: type
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
groups:
  tag_Name_your_tag_name: 
    ansible_user: ubuntu  
